### ISSUE TITLE
It shows Loading... but not preview

### ISSUE THREAD

**Issue by Archie-2021** [slavistan/lf-gadgets#15]
Should I use zsh as my shell for this to work? I installed all the prerequisite packages (including zsh) but it is not working.

**Comment by slavistan** [comment]
Hi! Which gadget does not preview?

**Comment by Archie-2021** [comment]
> Hi! Which gadget does not preview?

Hey, non of them, it doesn't even show the simple text files anymore.

PS. Sorry I didn't understand the question properly, It is lf-ueberzug I am talking about.

**Comment by Archie-2021** [comment]
![image](https://user-images.githubusercontent.com/85870778/203948129-1ba85933-ed21-4a7c-b13a-f908af468583.png)

**Comment by Archie-2021** [comment]
i
![image](https://user-images.githubusercontent.com/85870778/203948824-0c5ac9e1-d4e1-4f79-931b-e7f29fe16371.png)

Also it doesn't exit properly and crashes on exit.

**Comment by slavistan** [comment]
Alright, I'll have a look. Haven't updated the scripts to the newer versions of `lf`.

**Comment by Archie-2021** [comment]
> Alright, I'll have a look. Haven't updated the scripts to the newer versions of `lf`.

Thanks

**Comment by slavistan** [comment]
I've checked the ueberzug and youtube gadgets quickly, and everything seems to work just fine. May I kindly ask you to post the outputs of the following commands:

```
uname -a
command -v lf
lf -version
ueberzug version
jq --version
youtube-dl --version
zsh --version
```

**Comment by Archie-2021** [comment]
> I've checked the ueberzug and youtube gadgets quickly, and everything seems to work just fine. May I kindly ask you to post the outputs of the following commands:
> 
> ```
> uname -a
> command -v lf
> lf -version
> ueberzug version
> jq --version
> youtube-dl --version
> zsh --version
> ```
I've checked the ueberzug and youtube gadgets quickly, and everything seems to work just fine. May I kindly ask you to post the outputs of the following commands:

```
uname -a
command -v lf
lf -version
ueberzug version
jq --version
youtube-dl --version
zsh --version
```
I've checked the ueberzug and youtube gadgets quickly, and everything seems to work just fine. May I kindly ask you to post the outputs of the following commands:

```
uname -a
command -v lf
lf -version
ueberzug version
jq --version
youtube-dl --version
zsh --version
```
I've checked the ueberzug and youtube gadgets quickly, and everything seems to work just fine. May I kindly ask you to post the outputs of the following commands:

```
uname -a
command -v lf
lf -version
ueberzug version
jq --version
youtube-dl --version
zsh --version
```

**Comment by Archie-2021** [comment]
I've checked the ueberzug and youtube gadgets quickly, and everything seems to work just fine. May I kindly ask you to post the outputs of the following commands:

```
uname -a
command -v lf
lf -version
ueberzug version
jq --version
youtube-dl --version
zsh --version
```

```
6.0.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 16 Nov 2022 17:01:17 +0000 x86_64 GNU/Linux
/usr/bin/lf
27
18.1.9
jq-1.6
2021-12.17
zsh 5.9 (x86_64-pc-linux-gnu)
```

**Comment by slavistan** [comment]
Looks good to me. The next step is to verify that you can run `ueberzug` overlays, as that seems to be the problem on your side. Unfortunately, `ueberzug` apparently isn't maintained anymore so you'll have to check out the README of one of the forks.

Also: you _are_ using X11, right? You're not on wayland, are you?

**Comment by Archie-2021** [comment]
> Looks good to me. The next step is to verify that you can run `ueberzug` overlays, as that seems to be the problem on your side. Unfortunately, `ueberzug` apparently isn't maintained anymore so you'll have to check out the README of one of the forks.
> 
> Also: you _are_ using X11, right? You're not on wayland, are you?

Can you link one, I am not sure what you are referring here.

Yes I am on X , using EOS.

**Comment by slavistan** [comment]
https://github.com/seebye/ueberzug/tree/18.1.9

`ueberzug` is the program used to create overlays of images on top of terminal emulators, creating the impression of viewing images or videos "inside the terminal". I assume that these don't work on your side. Try getting to run a minimal working example with ueberzug.

>using EOS

What is EOS?

**Comment by fralnz** [comment]
Hi, I have a the same issue. After closing lf with q, I have to manually kill the process with `Ctrl-C` two times, this is the output:
```
^C/home/fra/.config/lf/lf-ueberzug-cleaner: 3: cannot create /tmp/lf-ueberzug-vuCz1G/fifo: Interrupted system call
^C/home/fra/.config/lf/lf-ueberzug-cleaner: 3: cannot create /tmp/lf-ueberzug-vuCz1G/fifo: Interrupted system call
cleanup:kill:2: kill 12344 failed: no such process
cleanup:kill:2: kill 12344 failed: no such process
```

**Comment by slavistan** [comment]
@WalkingGarbage Hi. Can you check whether ueberzug overlays work in principle on your setup?

https://github.com/seebye/ueberzug/tree/18.1.9

**Comment by fralnz** [comment]
I'm sorry, I'm not really sure what you mean. I tried doing `ueberzug layer -l 613356.png` but:
```
Traceback (most recent call last):
  File "/usr/bin/ueberzug", line 33, in <module>
    sys.exit(load_entry_point('ueberzug==18.1.9', 'console_scripts', 'ueberzug')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ueberzug/__main__.py", line 55, in main
    module.main(options)
  File "/usr/lib/python3.11/site-packages/ueberzug/layer.py", line 204, in main
    display = xutil.get_display()
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ueberzug/xutil.py", line 60, in get_display
    return Xdisplay.Display()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.11/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
Fatal Python error: bool_dealloc: deallocating True or False: bug likely caused by a refcount error in a C extension
Python runtime state: finalizing (tstate=0x00007fd98bf39b38)

Current thread 0x00007fd98bfe8740 (most recent call first):
  Garbage-collecting
  <no Python frame>
zsh: IOT instruction  ueberzug layer -l 613356.png
```
I tried installing ueberzug from pip3 but it gave me errors: `Could not find a version that satisfies the requirement ueberzug (from versions: none)`
